### ISSUE TITLE
The plugin has repeating the effect in all commands after the first execution the effect

### ISSUE THREAD

**Issue by jrbytes** [BrianIshii/git-falcon9#17]
After the commands: `git clone` and `git push`
The plugin repeat always the effect in all commands.

SO: Linux Ubuntu 20.04
Hyper: 3.0.2
git-falcon9: 1.0.16

**Comment by Suvink** [comment]
Have the same issue. The plugin repeats itself on every command after the first `git` execution.

MacOS Mojave 10.14.6
Hyper: 3.0.2 (stable)
git-falcon9 (1.0.16)

**Comment by roman-pinchuk** [comment]
The same issue

OS: macOS 10.15.5
Term: Hyper 3.0.2 (Stable)

**Comment by BrianIshii** [comment]
@jrbytes @Suvink @roman-pinchuk sorry for the delay. I put in a quick fix that should hopefully take care of the issue. Let me know if it works!

**Comment by Suvink** [comment]
Cool. Will check it out and let you know soon!

**Comment by Suvink** [comment]
@BrianIshii Everything works fine. Thanks

**Comment by jrbytes** [comment]
@BrianIshii thank's. I tested `git clone` and `git push`.

SO: Ubuntu 20.04
